# regen_paths.tcl — rewrites nastran_control.mac with this folder's own
# absolute path. Run after copying this folder to a new machine:
#     tclsh regen_paths.tcl
# Does not need the CAE tool installed — plain tclsh is enough (or run it
# from inside the CAE tool's own Tcl console instead).

set here [file normalize [file dirname [info script]]]
set here [string map {\\ /} $here]

set mac "// Nastran Control Tool - standalone User page buttons.
// Generated by regen_paths.tcl on this machine.
// Keep comments short, plain ASCII, and never repeat a star command name
// here - the CAE tool's macro-file parser is not comment-safe around that.

*createtext(1, \"-- Nastran Control --\", 0, 0)
*createbutton(1, \"NC Launch\", 0, 0, 10, GREEN, \"Open Nastran Control tool (scan + table)\", \"EvalTcl\", \"$here/nastran_control.tcl\")
*createbutton(1, \"NC Save\",   0, 0, 10, CYAN,  \"Save current Nastran Control session state to CSV\", \"EvalTcl\", \"$here/nc_save.tcl\")
*createbutton(1, \"PPT Bridge\", 0, 0, 10, YELLOW, \"Load the PowerPoint bridge watcher: capture model window/square PNG and Get Model Info requests from PowerPoint (run once per new CAE tool session)\", \"EvalTcl\", \"<PPTX_TOOL_PATH>/hm_ppt_bridge/hm_ppt_request_watcher.tcl\")

*beginmacro(\"EvalTcl\")
*evaltclscript(\$1,0)
*endmacro()

*setactivepage(1)
"

set out [file join $here nastran_control.mac]
set fp [open $out w]
puts -nonewline $fp $mac
close $fp
puts "Wrote $out"
puts "Paths point at: $here"
